const { withPodfile, withPodfileProperties, withXcodeProject } = require('@expo/config-plugins');

// The app's own build target inside the generated Xcode project. Must match
// the PBXNativeTarget "name" in ios/qRemote.xcodeproj/project.pbxproj (see
// app.config.js's `expo.name`) so updateBuildProperty below only touches this
// target's Debug/Release configs, not the project-level defaults or any
// future extension target.
const APP_TARGET_NAME = 'qRemote';

// The macOS deployment target given to every Pods target below. Kept at or
// below the app target's own MACOSX_DEPLOYMENT_TARGET (13.4, set by the Expo
// template in ios/qRemote.xcodeproj) so nothing in Pods requires a newer
// macOS than the app itself does, while staying inside the range Xcode's
// current SDK accepts (12.0 to current).
const PODS_MACOSX_DEPLOYMENT_TARGET = '12.0';

// The iOS deployment target forced on every Pods target. Xcode 27 derives a
// Catalyst build's effective macOS deployment target from
// IPHONEOS_DEPLOYMENT_TARGET (MACOSX_DEPLOYMENT_TARGET is ignored for the
// Catalyst variant) and its mapping table has no entry for 15.1, the value
// React Native 0.86 pods declare: 15.0 -> 12.0, 15.2 -> 12.1, 16.4 -> 13.3,
// but 15.1 -> 10.15, which the SDK then rejects ("range of supported
// deployment target versions is 12.0 to ..."). Aligning pods on the app
// target's own deployment target (Expo SDK 57 = 16.4) sidesteps the gap and
// is safe: a pod never needs to run on an older iOS than the app itself.
const PODS_IPHONEOS_DEPLOYMENT_TARGET = '16.4';

// react_native_pods.rb's react_native_post_install(...) call is generated by
// Expo's Podfile template with this literal keyword argument. Flipping it to
// true makes react_native_pods.rb call
// ReactNativePodsUtils.apply_mac_catalyst_patches(installer) (see
// node_modules/react-native/scripts/cocoapods/utils.rb), which fixes bundle
// code-sign identity, dead-code-stripping and Swift library search paths for
// every pod aggregate target when building the Mac Catalyst destination.
const OLD_MAC_CATALYST_FLAG = ':mac_catalyst_enabled => false';
const NEW_MAC_CATALYST_FLAG = ':mac_catalyst_enabled => true';

// Belt-and-suspenders alongside apply_mac_catalyst_patches: most third-party
// pods in this app are pure Swift/ObjC source (no prebuilt binary slice to
// worry about), but their podspecs were never authored with Mac Catalyst in
// mind, so CocoaPods doesn't mark their generated pod targets as buildable
// for the Catalyst destination unless SUPPORTS_MACCATALYST is forced on. A
// pod that genuinely ships a non-Catalyst prebuilt binary would fail to link
// even with this set; that gets excluded by name here instead (see the
// EXCLUDED_FROM_MACCATALYST list), not by leaving the flag off everywhere.
const EXCLUDED_FROM_MACCATALYST = [];

const POST_INSTALL_MARKER = '# withMacCatalyst: force SUPPORTS_MACCATALYST on pod targets';
const POST_INSTALL_BLOCK = `  ${POST_INSTALL_MARKER}
  installer.pods_project.targets.each do |target|
    next if ${JSON.stringify(EXCLUDED_FROM_MACCATALYST)}.include?(target.name)
    target.build_configurations.each do |config|
      config.build_settings['SUPPORTS_MACCATALYST'] = 'YES'
      # Pod targets here are iOS-only podspecs (no s.osx.deployment_target),
      # so CocoaPods never sets MACOSX_DEPLOYMENT_TARGET on them and Xcode
      # falls back to its old built-in default (10.15) for the Mac Catalyst
      # destination, which current Xcode rejects (min supported is 12.0).
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = ${JSON.stringify(PODS_MACOSX_DEPLOYMENT_TARGET)}
      # See PODS_IPHONEOS_DEPLOYMENT_TARGET in plugins/withMacCatalyst.js:
      # Xcode derives the Catalyst macOS target from this value and 15.1
      # maps to an unsupported 10.15.
      ios_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      if ios_target.nil? || Gem::Version.new(ios_target) < Gem::Version.new(${JSON.stringify(PODS_IPHONEOS_DEPLOYMENT_TARGET)})
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = ${JSON.stringify(PODS_IPHONEOS_DEPLOYMENT_TARGET)}
      end
    end
  end
  # The Pods.xcodeproj PROJECT-level (root PBXProject) config has no
  # MACOSX_DEPLOYMENT_TARGET / SUPPORTS_MACCATALYST of its own; CocoaPods only
  # ever writes per-target settings (above). Setting it here too so nothing in
  # the dependency graph falls back to Xcode's old default through the
  # project level instead of a target level.
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['SUPPORTS_MACCATALYST'] = 'YES'
    config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = ${JSON.stringify(PODS_MACOSX_DEPLOYMENT_TARGET)}
  end
`;

/**
 * Patches the generated Podfile and Xcode project so `qRemote` builds as a
 * Mac Catalyst target. `ios/` is regenerated by every `expo prebuild` (npm
 * run xcode), so this must be a config plugin rather than a hand-edit of the
 * generated Podfile / project.pbxproj; see AGENTS.md "iOS Native Workflow".
 *
 * Gating note: this plugin only changes what the app is capable of building
 * as. It does not turn on any Mac-specific UI by itself; every desktop code
 * path in the JS/TS layer stays gated on `useShell().idiom === 'mac'`
 * (hooks/useLayoutIdiom.ts, true when Platform.isMacCatalyst), so iPhone and
 * iPad behaviour is unaffected by this plugin existing.
 *
 * BUILD STATUS (verified 2026-09-10, Xcode 27.0 beta, Build 27A5237l): a
 * from-scratch `expo prebuild --clean` + `pod install` + Catalyst build
 * succeeds end to end with this plugin (BUILD SUCCEEDED, universal
 * arm64 + x86_64 bundle, UIDeviceFamily = [6]). Two root causes had to be
 * fixed before it did:
 *   1. Xcode 27 derives the Catalyst macOS deployment target from
 *      IPHONEOS_DEPLOYMENT_TARGET and has no table entry for 15.1 (the value
 *      every React Native 0.86 pod declares), so those pods resolved to
 *      10.15 and the build description was rejected (90 errors of the shape
 *      "The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to
 *      10.15, but the range of supported deployment target versions is 12.0
 *      to 27.0.x"). Fix: PODS_IPHONEOS_DEPLOYMENT_TARGET below.
 *   2. Expo SDK 57's precompiled ExpoModulesCore.xcframework has no
 *      maccatalyst slice ("no such module 'ExpoModulesCore'"). Fix: the
 *      EXPO_USE_PRECOMPILED_MODULES Podfile property below.
 * Verify with:
 *   QREMOTE_MAC_CATALYST=1 npx expo prebuild -p ios --no-install --clean
 *   (cd ios && LANG=en_US.UTF-8 pod install)
 *   xcodebuild -workspace ios/qRemote.xcworkspace -scheme qRemote \
 *     -configuration Debug \
 *     -destination 'generic/platform=macOS,variant=Mac Catalyst' \
 *     CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY= -derivedDataPath ios/build build
 */
module.exports = function withMacCatalyst(config) {
  // Opt-in gate: the Catalyst-specific Podfile and Xcode-project changes are
  // only applied when QREMOTE_MAC_CATALYST=1 is set at prebuild time. Without
  // it the generated iOS project is byte-identical to what Expo produces on
  // its own, so the App Store / EAS iPhone and iPad pipeline is untouched
  // (EXPO_USE_PRECOMPILED_MODULES=false alone would slow every clean iOS
  // build by compiling all Expo modules from source). The plugin stays
  // registered in app.config.js so enabling Mac is one env var, not a
  // re-registration. `npm run xcode:mac` sets it.
  if (process.env.QREMOTE_MAC_CATALYST !== '1') {
    return config;
  }

  // Expo SDK 57 links ExpoModulesCore (and the other Expo modules) as
  // precompiled xcframeworks by default. Those xcframeworks ship ios-arm64 and
  // ios-arm64_x86_64-simulator slices only, no maccatalyst slice, so the
  // Catalyst build dies with "no such module 'ExpoModulesCore'" in the first
  // Swift module that imports it. Setting this Podfile property makes the
  // generated Podfile export EXPO_USE_PRECOMPILED_MODULES=0 before pod
  // install, so every Expo module compiles from source for all destinations.
  // Cost: slower clean iOS builds. React Native core keeps its prebuilt
  // React.xcframework, which does carry an ios-arm64_x86_64-maccatalyst slice.
  config = withPodfileProperties(config, (config) => {
    config.modResults.EXPO_USE_PRECOMPILED_MODULES = 'false';
    return config;
  });

  config = withPodfile(config, (config) => {
    let contents = config.modResults.contents;

    if (contents.includes(POST_INSTALL_MARKER)) {
      // Already patched (e.g. re-running prebuild) - leave it alone.
      return config;
    }

    if (!contents.includes(OLD_MAC_CATALYST_FLAG)) {
      throw new Error(
        'withMacCatalyst: expected Podfile "' +
          OLD_MAC_CATALYST_FLAG +
          '" not found. The Expo Podfile template likely changed. Update plugins/withMacCatalyst.js to match.',
      );
    }
    contents = contents.replace(OLD_MAC_CATALYST_FLAG, NEW_MAC_CATALYST_FLAG);

    const postInstallMatch = contents.match(/post_install do \|installer\|\n/);
    if (!postInstallMatch) {
      throw new Error(
        'withMacCatalyst: expected Podfile "post_install do |installer|" block not found. ' +
          'The Expo Podfile template likely changed. Update plugins/withMacCatalyst.js to match.',
      );
    }
    const insertAt = postInstallMatch.index + postInstallMatch[0].length;
    contents = contents.slice(0, insertAt) + POST_INSTALL_BLOCK + contents.slice(insertAt);

    config.modResults.contents = contents;
    return config;
  });

  config = withXcodeProject(config, (config) => {
    const project = config.modResults;

    // pbxTargetByName's caller (xcode's updateBuildProperty) silently skips
    // every configuration when the target name doesn't match instead of
    // throwing, so a rename of expo.name would drop all the build settings
    // below with zero signal. Fail loudly instead.
    if (!project.pbxTargetByName(APP_TARGET_NAME)) {
      throw new Error(
        'withMacCatalyst: target "' +
          APP_TARGET_NAME +
          '" not found in the generated Xcode project. Update APP_TARGET_NAME in ' +
          'plugins/withMacCatalyst.js to match expo.name.',
      );
    }

    // SUPPORTS_MACCATALYST: the actual on/off switch for building qRemote as
    // a Mac Catalyst destination at all.
    project.updateBuildProperty('SUPPORTS_MACCATALYST', 'YES', undefined, APP_TARGET_NAME);

    // DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: lets the Catalyst build
    // use a distinct derived bundle id so it can install side by side with
    // the iOS build on the same Mac during development, matching how Xcode's
    // own "Mac" checkbox behaves.
    project.updateBuildProperty(
      'DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER',
      'YES',
      undefined,
      APP_TARGET_NAME,
    );

    // TARGETED_DEVICE_FAMILY: "6" is the Mac Catalyst device family member
    // (1 = iPhone, 2 = iPad, 6 = Mac). This is the actual mechanism behind
    // Xcode's "Mac Catalyst Interface: Optimize for Mac" popup (as opposed to
    // its default "Scaled to Match iPad"). Xcode has no separate build
    // setting for that popup; it works purely by writing this device family
    // list into the built Info.plist as UIDeviceFamily, and UIKit reads "6"
    // present in UIDeviceFamily to report
    // UIDevice.current.userInterfaceIdiom == .mac instead of the scaled
    // .pad idiom. Confirmed against Apple's Mac Catalyst user-interface-idiom
    // guidance and cross-checked against Tuist's and XcodeGen's Mac Catalyst
    // support (both add "6" to TARGETED_DEVICE_FAMILY for the same reason).
    // Keeping "1,2" alongside it means the same built app still declares
    // iPhone/iPad support for the plain iOS destinations.
    project.updateBuildProperty('TARGETED_DEVICE_FAMILY', '"1,2,6"', undefined, APP_TARGET_NAME);

    return config;
  });

  return config;
};
