name: Create builds
jobs:
  ios_preview:
    name: Build iOS device
    type: build
    params:
      platform: ios
      profile: preview
  ios_prod:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: production
