name: Build

on:
  push:
    branches:
      - main
jobs:
  build_ios:
    name: Build iOS App
    type: build
    params:
      platform: ios
      profile: production
  build_android:
    name: Build Android App
    type: build
    params:
      platform: android
      profile: production
 
